from .chapter_1_arena import Chapter1
from .chapter_2_escape import Chapter2
from .chapter_3_pirates import Chapter3
from .chapter_4_white_cube import Chapter4
from .chapter_5_black_cube import Chapter5
from .chapter_6_prime_lagoon import Chapter6
from .chapter_7_worm_brothers import Chapter7
from .chapter_8_alloy import Chapter8
from .chapter_9_droid import Chapter9
from .chapter_10_rovaam_hell import Chapter10
from .chapter_11_final import Chapter11
from .epilogue import Epilogue